name :ci pipeline
"on":
  push:
    branches:
      - main

jobs:
  build:
  runs-on:ubunta-latest
  steps:
    -name:checkout code
    uses:action/checkout@v5

    -name:set up node.js
    uses:actions/set up-node@v3
    with:
        node-version: 16

    -name:install dependencies
    run:npm install

    -name:run test
    run:npn tests